# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-is-persistent_state_machine}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["michael"]
  s.date = %q{2010-01-04}
  s.description = %q{A persistent State Machine for DataMapper}
  s.email = %q{ma@zive.at}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "dm-is-persistent_state_machine.gemspec",
     "lib/dm-is-persistent_state_machine.rb",
     "lib/dm-is-persistent_state_machine/is/persistent_state_machine.rb",
     "test/helper.rb",
     "test/test_dm-is-persistent_state_machine.rb"
  ]
  s.homepage = %q{http://github.com/michael/dm-is-persistent_state_machine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A persistent State Machine for DataMapper}
  s.test_files = [
    "test/helper.rb",
     "test/test_dm-is-persistent_state_machine.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

